#挂网企业类型
BUSINESS_COMPANY = 1
MANUFACTURING_ENTERPRISE = 2
HANG_TYPE_CHOICES = (
    (BUSINESS_COMPANY,'商业公司'),
    (MANUFACTURING_ENTERPRISE,'生产企业'),
)
#购买形式
MIDDLE_BAG = 1
DISMOUNTED = 2
BUY_METHOD_CHOICES = (
    (MIDDLE_BAG, '中包'),
    (DISMOUNTED, '拆零'),
)
#支付方式
IMMEDIATE_PAYMENT = '0'
DELAY_THIRTY_DAYS = '1'
DELAY_FORTY_FIVE_DAYS ='2'
DELAY_SIXTY_DAYS = '3'
PAY_METHOD_CHOICES =(
    (IMMEDIATE_PAYMENT,'立即支付'),
    (DELAY_THIRTY_DAYS,'延期三十天'),
    (DELAY_FORTY_FIVE_DAYS,'延期四十五天'),
    (DELAY_SIXTY_DAYS,'延期六十天'),
)